// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adb} from '../models';
import {core} from '../models';

export function ClearCacheData():void;

export function GetDisplay(arg1:string):Promise<adb.Display>;

export function GetFirstImageInfo():Promise<core.ImageInfo>;

export function GetImageFiles():Promise<Array<string>>;

export function ListDevices():Promise<Array<adb.Device>>;

export function SetAutoSwipeOff():Promise<Error>;

export function SetAutoSwipeOn(arg1:adb.SwipeEvent,arg2:number):Promise<Error>;

export function SetPointerLocationOff(arg1:string):Promise<Error>;

export function SetPointerLocationOn(arg1:string):Promise<Error>;

export function Start(arg1:string,arg2:number):Promise<Error>;

export function StartAnalyse(arg1:core.ImageRectInfo,arg2:number):Promise<Error>;

export function StartRecord(arg1:string):Promise<Error>;

export function StartTransform():Promise<Error>;

export function StopProcessing():Promise<Error>;

export function StopRecord(arg1:string):Promise<Error>;

export function StopScrcpyServer(arg1:string):Promise<Error>;

export function StopTransform():void;
