// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearImages() {
  return window['go']['app']['Api']['ClearImages']();
}

export function ClearVideos() {
  return window['go']['app']['Api']['ClearVideos']();
}

export function ListDevices() {
  return window['go']['app']['Api']['ListDevices']();
}

export function SetPointerLocationOff(arg1) {
  return window['go']['app']['Api']['SetPointerLocationOff'](arg1);
}

export function SetPointerLocationOn(arg1) {
  return window['go']['app']['Api']['SetPointerLocationOn'](arg1);
}

export function StartAnalyse() {
  return window['go']['app']['Api']['StartAnalyse']();
}

export function StartRecord(arg1) {
  return window['go']['app']['Api']['StartRecord'](arg1);
}

export function StartTransform() {
  return window['go']['app']['Api']['StartTransform']();
}

export function StopAnalyse() {
  return window['go']['app']['Api']['StopAnalyse']();
}

export function StopProcessing() {
  return window['go']['app']['Api']['StopProcessing']();
}

export function StopRecord(arg1) {
  return window['go']['app']['Api']['StopRecord'](arg1);
}

export function StopTransform() {
  return window['go']['app']['Api']['StopTransform']();
}
