// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCacheData() {
  return window['go']['app']['Api']['ClearCacheData']();
}

export function GetDisplay(arg1) {
  return window['go']['app']['Api']['GetDisplay'](arg1);
}

export function GetFirstImageInfo() {
  return window['go']['app']['Api']['GetFirstImageInfo']();
}

export function GetImageFiles() {
  return window['go']['app']['Api']['GetImageFiles']();
}

export function GetPhysicalSize(arg1) {
  return window['go']['app']['Api']['GetPhysicalSize'](arg1);
}

export function InputSwipe(arg1, arg2) {
  return window['go']['app']['Api']['InputSwipe'](arg1, arg2);
}

export function IsAppReady() {
  return window['go']['app']['Api']['IsAppReady']();
}

export function ListDevices() {
  return window['go']['app']['Api']['ListDevices']();
}

export function ListRecords() {
  return window['go']['app']['Api']['ListRecords']();
}

export function SetAutoSwipeOff() {
  return window['go']['app']['Api']['SetAutoSwipeOff']();
}

export function SetAutoSwipeOn(arg1, arg2) {
  return window['go']['app']['Api']['SetAutoSwipeOn'](arg1, arg2);
}

export function SetPointerLocationOff(arg1) {
  return window['go']['app']['Api']['SetPointerLocationOff'](arg1);
}

export function SetPointerLocationOn(arg1) {
  return window['go']['app']['Api']['SetPointerLocationOn'](arg1);
}

export function Start(arg1, arg2) {
  return window['go']['app']['Api']['Start'](arg1, arg2);
}

export function StartAnalyse(arg1, arg2) {
  return window['go']['app']['Api']['StartAnalyse'](arg1, arg2);
}

export function StartRecord(arg1) {
  return window['go']['app']['Api']['StartRecord'](arg1);
}

export function StartTransform() {
  return window['go']['app']['Api']['StartTransform']();
}

export function StartWithVideo(arg1) {
  return window['go']['app']['Api']['StartWithVideo'](arg1);
}

export function StopRunner() {
  return window['go']['app']['Api']['StopRunner']();
}

export function StopScrcpyServer(arg1) {
  return window['go']['app']['Api']['StopScrcpyServer'](arg1);
}

export function StopTransform() {
  return window['go']['app']['Api']['StopTransform']();
}

export function Transform(arg1) {
  return window['go']['app']['Api']['Transform'](arg1);
}

export function UploadFile(arg1) {
  return window['go']['app']['Api']['UploadFile'](arg1);
}
