// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCacheData() {
  return window['go']['app']['Api']['ClearCacheData']();
}

export function GetDisplay(arg1) {
  return window['go']['app']['Api']['GetDisplay'](arg1);
}

export function GetFirstImageInfo() {
  return window['go']['app']['Api']['GetFirstImageInfo']();
}

export function ListDevices() {
  return window['go']['app']['Api']['ListDevices']();
}

export function SetAutoSwipeOff() {
  return window['go']['app']['Api']['SetAutoSwipeOff']();
}

export function SetAutoSwipeOn(arg1, arg2) {
  return window['go']['app']['Api']['SetAutoSwipeOn'](arg1, arg2);
}

export function SetPointerLocationOff(arg1) {
  return window['go']['app']['Api']['SetPointerLocationOff'](arg1);
}

export function SetPointerLocationOn(arg1) {
  return window['go']['app']['Api']['SetPointerLocationOn'](arg1);
}

export function Start(arg1, arg2) {
  return window['go']['app']['Api']['Start'](arg1, arg2);
}

export function StartAnalyse(arg1, arg2) {
  return window['go']['app']['Api']['StartAnalyse'](arg1, arg2);
}

export function StartRecord(arg1) {
  return window['go']['app']['Api']['StartRecord'](arg1);
}

export function StartTransform() {
  return window['go']['app']['Api']['StartTransform']();
}

export function StopProcessing() {
  return window['go']['app']['Api']['StopProcessing']();
}

export function StopRecord(arg1) {
  return window['go']['app']['Api']['StopRecord'](arg1);
}

export function StopScrcpyServer(arg1) {
  return window['go']['app']['Api']['StopScrcpyServer'](arg1);
}

export function StopTransform() {
  return window['go']['app']['Api']['StopTransform']();
}
