// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function StartRecord(arg1) {
  return window['go']['main']['App']['StartRecord'](arg1);
}

export function StopProcessing() {
  return window['go']['main']['App']['StopProcessing']();
}

export function StopRecord(arg1) {
  return window['go']['main']['App']['StopRecord'](arg1);
}
