// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearImages() {
  return window['go']['main']['App']['ClearImages']();
}

export function ClearVideos() {
  return window['go']['main']['App']['ClearVideos']();
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function StartAnalyse() {
  return window['go']['main']['App']['StartAnalyse']();
}

export function StartRecord(arg1) {
  return window['go']['main']['App']['StartRecord'](arg1);
}

export function StartTransform() {
  return window['go']['main']['App']['StartTransform']();
}

export function StopAnalyse() {
  return window['go']['main']['App']['StopAnalyse']();
}

export function StopProcessing() {
  return window['go']['main']['App']['StopProcessing']();
}

export function StopRecord(arg1) {
  return window['go']['main']['App']['StopRecord'](arg1);
}

export function StopTransform() {
  return window['go']['main']['App']['StopTransform']();
}
