// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adb} from '../models';

export function ClearImages():void;

export function ClearVideos():void;

export function ListDevices():Promise<Array<adb.Device>>;

export function StartAnalyse():void;

export function StartRecord(arg1:string):void;

export function StartTransform():void;

export function StopAnalyse():void;

export function StopProcessing():void;

export function StopRecord(arg1:string):void;

export function StopTransform():void;
